import { GoogleGenAI } from "@google/genai";
import { BASE_PROMPT, ATMOSPHERE_PROMPT } from '../constants';
import { StyleOption } from '../types';

export const generateTryOnImage = async (
  imageFile: File,
  style: StyleOption
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("Missing API Key");
  }

  const ai = new GoogleGenAI({ apiKey });

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result as string;
        // Remove data URL prefix (e.g. "data:image/jpeg;base64,")
        const base64 = result.split(',')[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  try {
    const base64Data = await fileToBase64(imageFile);
    
    // Construct a prompt that asks to apply the style to the person in the image
    const prompt = `Transform the clothing of the person in this image. ${style.promptPart}. ${BASE_PROMPT}. ${ATMOSPHERE_PROMPT}. Maintain the person's identity, pose, and background as much as possible.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: imageFile.type || 'image/jpeg',
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64EncodeString = part.inlineData.data;
        return `data:image/png;base64,${base64EncodeString}`;
      }
    }
    
    throw new Error("No image generated by Gemini");

  } catch (error) {
    console.error("Gemini API Error:", error);
    // Re-throw to be handled by the UI
    throw error;
  }
};